### ISSUE TITLE
Update typedoc

### ISSUE THREAD

**Issue by bryevdv** [rapidsai/node-rapids#111]
Currently after TS 4.2.2 update:
```
rapids-0.18 ❯ npm run doc

> @nvidia/cudf@0.0.1 doc /home/bryan/dev/rapids/rapids-js/modules/cudf
> rimraf doc && typedoc --options typedoc.js

Warning: You are running with an unsupported TypeScript version! TypeDoc supports 3.9, 4.0, 4.1
```

**Comment by AjayThorve** [comment]
related typedoc issue -> https://github.com/TypeStrong/typedoc/issues/1517

**Comment by bryevdv** [comment]
:crossed_fingers:  its released soon tho FWIW docs still seem to build fine at least to a glance

**Comment by AjayThorve** [comment]
yep, I built them with the warning yesterday, and github-pages site seems to be fine

**Comment by trxcllnt** [comment]
Done in https://github.com/rapidsai/node-rapids/pull/115
