### ISSUE TITLE
Curl depdencies (may be) missing for some with `Develop without docker` section

### ISSUE THREAD

**Issue by exactlyallan** [rapidsai/node-rapids#124]
FYI on Ubuntu 20.04 (fairly fresh install) following [Dev w/o Docker](https://github.com/rapidsai/node-rapids/blob/main/docs/setup.md#develop-without-docker) I run into this error:

`Could NOT find CURL (missing: CURL_LIBRARY CURL_INCLUDE_DIR) 
CMake Error at CMakeLists.txt:477 (message):
  CMAKE_USE_SYSTEM_CURL is ON but a curl is not found!
`

Seems base CURL install is missing some dependencies - I resolved it with:
`sudo apt install libssl-dev libcurl4-openssl-dev`

**Comment by trxcllnt** [comment]
Ah yes, I think we need to install `libssl-dev` alongside `libcurl4-openssl-dev` in the `dev:install-cpp-dependencies` [script for Debian](https://github.com/rapidsai/node-rapids/blob/main/modules/core/bin/install-deps/debian.sh)
