### ISSUE TITLE
Add `Series.unique` and `Series.value_counts`

### ISSUE THREAD

**Issue by bryevdv** [rapidsai/node-rapids#132]
It's currently fairly cumbersome to just get the unique values in a Series, something like:
```
groups = df.groupBy({by: 'foo'}).getGroupd()
[....groups.keys.get('foo').gather(cudf.Series.new({type: new cudf.Int32, data:  groups.offsets})).toArrow()]
```

Python Cudf has [`unique`](https://docs.rapids.ai/api/cudf/stable/api.html?highlight=unique#cudf.core.series.Series.unique) and related [`value_counts`](https://docs.rapids.ai/api/cudf/stable/api.html?highlight=unique#cudf.core.series.Series.value_counts) that we can implement for `node-rapids`

**Comment by ajschmidt8** [comment]
I'll be working on fixing some of the demos in #125, but if no one gets to this issue by the time I'm done with those, then I can work on it.

**Comment by bryevdv** [comment]
@trxcllnt notes that there is libcudf [`drop_duplicates`](https://docs.rapids.ai/api/libcudf/stable/group__reorder__compact.html#gad5567643b290c5ee993383b4a97b8687) which is how python cudf implements `unique`. So it is probably good to emulate that (but a good first issue to start with still)
