### ISSUE TITLE
Start a FAQ?

### ISSUE THREAD

**Issue by bryevdv** [rapidsai/node-rapids#135]
With multiple cards I still have to make sure to set either 
*  `CUDA_VISIBLE_DEVICES=1` or 
* `docker-compose run --rm -e NVIDIA_VISIBLE_DEVICES=1 devel` 

in order for GL examples to display. This seems like the sort of thing that might be good to go in a FAQ. Are there any other gotchas we can/should provide guidance for?

cc @exactlyallan @trxcllnt @AjayThorve @ajschmidt8

**Comment by trxcllnt** [comment]
You should also be able to put `NVIDIA_VISIBLE_DEVICES=1` in your `.env`, but that's tangential to this issue :sweat_smile:. Yes, I think a FAQ can be useful.

**Comment by exactlyallan** [comment]
@AjayThorve this could be first thing to include in markdown + typescript docs format
