### ISSUE TITLE
Consider adding a `.env.sample` file

### ISSUE THREAD

**Issue by ajschmidt8** [rapidsai/node-rapids#142]
Our [npm scripts](https://github.com/rapidsai/node-rapids/blob/main/package.json#L26-L31) create a blank `.env` file when running the `Docker` commands, but users may not know what variables they can place in this file.

To help with this, adding a `.env.sample` file to the repo may be useful. This file could also include comments that describe what each variable does. An example file may look something like this:

```ini
PARALLEL_LEVEL=8 # Sets the number of processor cores to use for builds (?)
NODE_ENV=production # Enables production build optimizations when building TypeScript modules
```

**Comment by exactlyallan** [comment]
Really like this idea!
