### ISSUE TITLE
[BUG] replace_nulls(replace_policy) not working

### ISSUE THREAD

**Issue by AjayThorve** [rapidsai/node-rapids#156]
Series.replaceNulls(ReplacePolicy) throws an error.

```typescript
import {Series, ReplacePolicy} from '@rapidsai/cudf';
const a = Series.new([1, null, 3])
a.replaceNulls(ReplacePolicy.PRECEDING)
```
```bash
Uncaught Error: replace_nulls requires a Column, Scalar, or Boolean
    at Float64Series.replaceNulls (/home/ajay/new_dev/rapids-js/modules/cudf/build/js/series.js:116:49)
```

also tried sending a boolean, since it seems like cpp side is expecting a boolean, but it gets accepted as a scalar, and false is interpreted as 0, and true as 1

**Comment by trxcllnt** [comment]
@AjayThorve looks like it's expecting to be passed `keyof typeof ReplacePolicy`, i.e. `a.replaceNulls("PRECEDING")`.

**Comment by AjayThorve** [comment]
> @AjayThorve looks like it's expecting to be passed `keyof typeof ReplacePolicy`, i.e. `a.replaceNulls("PRECEDING")`.

@trxcllnt that results in a similar error:
![image](https://user-images.githubusercontent.com/20476096/117377516-4cab1d80-ae88-11eb-9217-9c8abba9e9f5.png)
